encyclopedia/urls.py
from django.urls import path

from . import views

app_name="wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("results", views.results, name="results"),
    path("create", views.create, name="create"),
    path("edit/<str:title>", views.edit, name="edit"),
    path("randompg", views.randompg, name="randompg")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
import random

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django import forms

import markdown2
from markdown2 import Markdown
markdowner = Markdown()

from . import util

# Form for the searchbar feature
class QueryForm(forms.Form):
    query = forms.CharField(label="",widget=forms.TextInput(attrs={'placeholder':'Search Encyclopedia'}))

# Form for creating new entry
class newEntryForm(forms.Form):
    newtitle = forms.CharField(label="Entry title",required=True,widget=forms.TextInput(attrs={'placeholder':'Title'}))
    newcontent = forms.CharField(label="",required=True,widget=forms.Textarea(attrs={'placeholder':'Enter entry content here..'}))

# Form for editting existing entry
class editForm(forms.Form):
    editbox=forms.CharField(label="", widget=forms.Textarea)

def index(request):
    """Home page listing titles of all available entries."""

    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "searchbar": QueryForm()
    })

def results(request):
    """Shows results of search query."""

    # Extracting query data
    form = QueryForm(request.POST)

    if form.is_valid():
        query = form.cleaned_data["query"]

        if util.get_entry(query)!=None:
            # Redirects to specified entry page if an exact match is found
            return HttpResponseRedirect(reverse('wiki:entry', kwargs={'title':query}))
        else:
            matches=[]

            # Selecting entry titles containing query as a substring
            for entry in util.list_entries():
                if query.lower() in str(entry.lower()):
                    matches.append(entry)

            if matches!=None:
                return render(request, "encyclopedia/results.html",{
                    "matches": matches,
                    "searchbar": QueryForm()
                    })
            else:
                return render(request, "encyclopedia/results.html",{
                    "message": "No results.",
                    "searchbar": QueryForm()
                    })

    else:
        return render(request, "encyclopedia/error.html",{
            "message": "Invalid query.",
            "searchbar": QueryForm()
        })

def entry(request, title):
    """Renders page that displays entry content."""

    # Displays error page if entry doesn't exist
    if util.get_entry(title)==None:
        return render(request, "encyclopedia/error.html",{
            "message": "The requested page was not found.",
            "searchbar": QueryForm()
        })

    # Converts markdown content to HTML
    entrycontent = markdowner.convert(util.get_entry(title))

    # Displays page with specified entry's contents
    return render(request, "encyclopedia/entry.html",{
        "title":title.capitalize(),
        "entrycontent": entrycontent,
        "searchbar": QueryForm()
    })

def create(request):
    """Allows user to create their own encyclopedia entry."""

    already_exists=False

    # Attempts to save new entry content inputted by user
    if request.method=="POST":

        # Extracting query data
        form = newEntryForm(request.POST)

        if form.is_valid():

            # Compares inputted title with existing entry titles
            for entry in util.list_entries():
                # Displays warning message if entry already exists
                if form.cleaned_data["newtitle"].lower() == entry.lower():
                    already_exists = True

            # Saves form contents as a new entry
            if already_exists == False:
                title = form.cleaned_data["newtitle"]
                content = form.cleaned_data["newcontent"]
                util.save_entry(title,content)
                return HttpResponseRedirect(reverse('wiki:entry', kwargs={'title':title}))
        else:
            return render(request, "encyclopedia/error.html",{
                "message": "Invalid inputs.",
                "searchbar": QueryForm()
            })

    return render(request, "encyclopedia/create.html",{
        "searchbar": QueryForm(),
        "form": newEntryForm(),
        "already_exists":already_exists
    })

def edit(request, title):
    """Allows user to edit existing entries."""

    # To pre-populate the editting text area with existing page content
    existing_content = util.get_entry(title)

    # When user tries to save their edits
    if request.method=="POST":

        # Extracting query data
        form = editForm(request.POST)

        if form.is_valid():

            # Replaces old entry with newly editted entry
            util.save_entry(title,form.cleaned_data["editbox"])
            return HttpResponseRedirect(reverse('wiki:entry', kwargs={'title':title}))

        else:
            return render(request, "encyclopedia/error.html",{
                "message": "Invalid inputs.",
                "searchbar": QueryForm()
            })

    return render(request, "encyclopedia/edit.html",{
        "searchbar": QueryForm(),
        "form": editForm(initial={'editbox':existing_content}),
        "title":title
    })

def randompg(request):
    """Redirects user to a random entry."""

    # Select a random item from list of entries
    list = util.list_entries()
    title = random.choice(list) # from Python's random module

    return HttpResponseRedirect(reverse('wiki:entry', kwargs={'title':title}))

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create New Page
{% endblock %}

{% block body %}
    <h1>Create a New Page</h1>
    <hr>

    <form action="{% url 'wiki:create' %}" method="post">
      {% csrf_token %}

      {% if already_exists %}
          <div class="form-group">
              <div class="alert alert-warning" role="alert">
                  Entry with this title already exists!
              </div>
          </div>
      {% endif %}

      <div class="form-group">
        {{form}}
      </div>

      <div class="form-group">
        <button type="submit" class="btn btn-primary mb-2">Save</button>
      </div>

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}
    <h1>Edit "{{title}}"</h1>
    <hr>

    <form action="{% url 'wiki:edit' title %}" method="post">
      {% csrf_token %}

      <div class="form-group">
        {{form}}
      </div>

      <div class="form-group">
        <button type="submit" class="btn btn-primary mb-2">Save</button>
      </div>
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}

    {{ entrycontent|safe }}

    <form action="{% url 'wiki:edit' title %}">
    <div class="form-group">
      <button class="btn btn-secondary">Edit</button>
    </div>
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}

    <h1>Error</h1>

    {{message}}

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'wiki:entry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:results' %}" method="post">
                    {% csrf_token %}
                   <!--<input class="search" type="text" name="q" placeholder="Search Encyclopedia">-->
                   {{searchbar}}
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:randompg' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Results</h1>
    <hr>
    {{ message }}
    <ul>
        {% for match in matches %}
            <li><a href="{% url 'wiki:entry' match %}">{{ match }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}